# Generated by Django 5.1.6 on 2025-02-26 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymg', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissuance',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 10, 58, 35, 810436, tzinfo=datetime.timezone.utc)),
        ),
    ]
