# Generated by Django 5.1.6 on 2025-02-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymg', '0005_bookissuance_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissuance',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
