# Generated by Django 5.1.6 on 2025-02-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymg', '0007_task_assigned_by_task_created_at_alter_task_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Done', 'Not Done'), ('Done', 'Done')], default='Not Done', max_length=10),
        ),
    ]
